### ISSUE TITLE
Need to add "about" route

### ISSUE THREAD

**Issue by Swarnendu0123** [Swarnendu0123/kbs-website#1]
when we go to  tbs other than home  eg-event and return to "about" it didn't work.

**Comment by Sathurshanan-Kandhasamy** [comment]
Hi [Swarnendu0123](https://github.com/Swarnendu0123), Can I work on this issue?

**Comment by Swarnendu0123** [comment]
> Hi [Swarnendu0123](https://github.com/Swarnendu0123), Can I work on this issue?

If you have the knowledge of react, then definitely yes.

**Comment by Swarnendu0123** [comment]
done #4
