### ISSUE TITLE
Implementing Signup and Signin Functionality with Firebase

### ISSUE THREAD

**Issue by Swarnendu0123** [Swarnendu0123/kbs-website#11]
The Kharagpur Blockchain Society's website aims to provide users with a seamless experience by implementing signup and signin functionality using Firebase authentication. This issue involves integrating Firebase Authentication into the website's backend to allow users to create accounts, sign in securely, and access exclusive features and resources.

**Comment by Parth-Hariyani3001** [comment]
I can try implement this I just need to explore firebase

**Comment by Swarnendu0123** [comment]
> I can try implement this I just need to explore firebase

Sure! But the key thing to remember is, deal with all the configurations with your environment variables. And don't push your `.env` file with the PR.
