### ISSUE TITLE
Mobile mode styles issue

### ISSUE THREAD

**Issue by Swarnendu0123** [Swarnendu0123/kbs-website#13]
# Issues
1. In the mobile mode the `sign in` button is not at centre.
2. the section bellow `GM Everyone!` is not at centre.

# Screenshot
![Screenshot (71)](https://github.com/Swarnendu0123/kbs-website/assets/94161758/64d06b03-8dfe-4639-a430-8c9382a17241)

**Comment by ElenaExposito** [comment]
Hello @Swarnendu0123! Can I take this issue?

**Comment by Swarnendu0123** [comment]
> Hello @Swarnendu0123! Can I take this issue?

Sure! Assigned to you.
