### ISSUE TITLE
Images not loading in homeImages component

### ISSUE THREAD

**Issue by varun-doshi** [Swarnendu0123/kbs-website#18]
The 5 images in the `homeImages` component are not loading correctly on the frontend.
The links to the images are blocked and not publicly accessible.

**Comment by Swarnendu0123** [comment]
Thanks @varun-doshi for addressing this issue.
Here is the [LinkedIn of Kharagpur Blockchain Society, IIT Kharagpur.](https://www.linkedin.com/posts/blockchainkgp_and-thats-a-wrap-blockchain-activity-7127641148323418112-8ynl?utm_source=share&utm_medium=member_android)
If you work on the issue, you can pick and choose these pictures from there.
(Dont choose any selection poster or announcement poster)

**Comment by Ashermuzic** [comment]
hey can i work on this one too ??

**Comment by Swarnendu0123** [comment]
> hey can i work on this one too ??

Yeah sure!!

**Comment by Ashermuzic** [comment]
Also the page refreshes when the component is clicked on. Is that done intentionally??

**Comment by Swarnendu0123** [comment]
> Also the page refreshes when the component is clicked on. Is that done intentionally??


It should redirect to the source of that picture, in that case, if you are using LinkedIn, it should redirect to LinkedIn.

**Comment by Swarnendu0123** [comment]
> hey can i work on this one too ??

If you are working, please raise the PR by 31 Jan.

**Comment by Swarnendu0123** [comment]
Done #19
